[mypy]
files = .
exclude = build/

pretty = true
show_error_codes = true

enable_error_code =
    ignore-without-code,
    possibly-undefined,
    truthy-bool,
    truthy-iterable,
strict = true
no_implicit_optional = true
strict_equality = true
warn_unreachable = true
warn_no_return = true
