[pytest]
addopts =
#   Testing behaviour
#   =================
    --strict-markers

#   Improve reporting
#   =================
    --tb=short
    --capture=fd

#   Plugins
#   =======
    --disable-plugin-autoload

filterwarnings =
    error::DeprecationWarning
    error::SyntaxWarning
    error::pytest.PytestCollectionWarning
xfail_strict = true
