[tox]
envlist = import_linter,mypy,py3{13,14},coverage

[testenv]
# Install wheels instead of source distributions for faster execution.
package = wheel
# Share the build environment between tox environments.
wheel_build_env = .pkg

dependency_groups =
  coverage
  tests
commands =
  coverage run --parallel-mode -m pytest {posargs:tests}

[testenv:coverage]
dependency_groups = coverage
depends = py3{13,14}
commands =
  coverage combine
  coverage report

[testenv:mypy]
dependency_groups = mypy
commands =
  mypy {posargs:.}

[testenv:import_linter]
dependency_groups = import_linter
commands =
  lint-imports {posargs}
