name: tests

on:
  pull_request:
  push:
    branches: [main]

# Only allow one instance of this workflow for each PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: |
            3.13
            3.14
          allow-prereleases: true
      - run: python -m pip install --group test_runners
      - run: tox run-parallel --parallel-no-spinner
        env:
          FORCE_COLOR: true
          TOX_OVERRIDE: testenv:mypy.set_env+=TERM=xterm-256color

  validate_commits:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: |
          git fetch origin main
          git branch main origin/main
      - uses: actions/setup-python@v6
        with:
          python-version-file: ".github/workflows/.python-version"
          cache: "pip"
      - run: python -m pip install --group test_runners
      - run: tox -e validate_commits
        env:
          FORCE_COLOR: true
